server:
  port: 8761

spring:
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=5m
  cloud:
    loadbalancer:
      cache:
        enabled: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false