server:
  port: 8082

spring:
  application:
    name: order-service
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=5m
  cloud:
    loadbalancer:
      cache:
        enabled: true
    openfeign:
      circuitbreaker:
        enabled: true

eureka:
  client:
    instance:
      instance-id: ${spring.application.name}:${server.port}
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        minimumNumberOfCalls: 5
    instances:
      userServiceClient:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 2s
    instances:
      userServiceClient:
        baseConfig: default