server:
  port: 8081

spring:
  application:
    name: user-service
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterAccess=5m
  cloud:
    loadbalancer:
      cache:
        enabled: true

eureka:
  eureka:
    instance:
      instance-id: ${spring.application.name}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true